### PR TITLE
adding characters sprite of adventurer's prairie

### PR DESCRIPTION
**Pull request by Iruuka**
Adding sprites of the adventurer's prairie.

TBD : 
- Add every others sprites,
- Trying to add units data in each tres files,

### CODE REVIEW

**Comment by Iruuka** [comment]
@aMytho I've added the sprites of characters apparing in the adventurer's prairie (i'll check again to be sure I haven't missed some)
Should I try to add the values of each in their tres files ?

**Comment by Iruuka** [comment]
I've just updated the data-info of each characters i've added. I've based myself on the wiki https://bravefrontierglobal.fandom.com/wiki/Adventurer%27s_Prairie

**Comment by aMytho** [comment]
I added the element as an enum so you can just select the element type in the editor. I had a few inconsistent element names, should be easier now.

**Comment by Iruuka** [comment]
@aMytho I just update the data using your enum.
I think that's everything for the character for the adventurer's prairie (i've just look at the Walkthrough https://www.youtube.com/watch?v=oBJ-k9D9sS4&list=PLsnvewLtPGlMPw6yLtfaq-5pD6LRCO-Ib&index=1&t=3729s)

I let you revew it and if everything looks good at your side, you can pull it !
I'll try to see if any of the adventurer's prairie is in already or not and i'll do a new pul lrequest for it.
If not, i'll try to fetch characters' sprite for the next stage !

**Comment by aMytho** [comment]
Looks good, I'll try to test it tomorrow.

**Comment by aMytho** [comment]
Looks good. I'll get this merged.  We can add the missing properties and other data later. Hopefully there is an easy way to handle the sprite sheets with multiple parts.

Thanks!

**Pull request merged**
