### PR TITLE
Adding French

### PR DESCRIPTION
**Pull request by ezemania2**
Just adding French title, description and dialogues

### CODE REVIEW

**Comment by aMytho** [comment]
Hello, thanks for the PR!

Are you wanting the french translation for code comments as shown in your PR, or to add translations that the end user can view? After skimming through the [translation documentation](https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html), it seems that we can use Gettext or CSV files for translations. These would be accessible to the user. This would be a bit of work to set up, but I could look into that.

If you just want to add the translations as code comments, I can merge it as is.

**Comment by ezemania2** [comment]
Hello I put the translit in comment because lack of knowledge

**Comment by aMytho** [comment]
That's alright.

We don't have a translation system set up yet. I'll try to look into how we can add other languages later this week.

**Comment by ezemania2** [comment]
sure thx

**Comment by aMytho** [comment]
I did some more research. I think we can add translations to the project, but it will be a lot of work to move everything over. I figure we can start with the level resources. I'm not going for a full recreation like recoded, but having translations for some things would be nice.

Do you have a preference between gettext or CSV files for translations? - [Godot Translations](https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html)

I haven't translated a project before so this is fairly new to me. I'm pretty busy so it may be a while before I can set that up, but I'm curious if you have an opinion. I may just merge this PR as is to have as a reference.

**Comment by ezemania2** [comment]
on my side I prefer using a csv. I always used csv for the other game where I'm working

**Comment by aMytho** [comment]
I did some research and I made a PR to add translations for the zones. I went with the spreadsheet (CSV) as suggested. I think it will work well. It was fairly simple to set up and it won't require that new areas have translations. They can be added if the user wants them.

[Translation PR](https://github.com/aMytho/brave-frontier-godot/pull/59)

I posted a link to the PR. If you think it is alright, I'll merge it. Once merged, you can edit the CSV in the `Adventure Prairie/Assets` directory and add the translations you want.

I'm assuming it is fine to have a separate CSV for each dungeon. I don't know how to have Godot to only import the translations when its needed though.

**Comment by ezemania2** [comment]
it looks ok for me

**Comment by aMytho** [comment]
I merged my translation PR. Once you've converted your PR to the CSV format I'll merge this one as well.

Let me know if you have any questions!

**Comment by ezemania2** [comment]
Sure! I'll let you know

**Comment by aMytho** [comment]
Implemented in #60

**Pull request closed without merging**
