### PR TITLE
Show unit thumbnail of connected account in unit list view

### PR DESCRIPTION
**Pull request by Iruuka**
Merge Request for Issue : https://github.com/aMytho/brave-frontier-godot/issues/14

Still point to fix : 
- Maybe update the way to get account info : https://github.com/aMytho/brave-frontier-godot/issues/14#issuecomment-1546643885
- There is a problem with the current code : while the game is launch, if you edit a page and then save, it appears the game crash with the error "Bad address index" (pretty sure I've added a cyclic reference somewhere. Need to take time to look at it) 
image
(some points are in french but the error is in english so all good)

### CODE REVIEW

**Comment by Iruuka** [comment]
@aMytho you can start to review this one if you have the time. Also, you can see a gif of what is implemented ==> https://drive.google.com/drive/folders/1x16JBn9A1A6OnbIpo1VmrzypN-krX87s?usp=sharing (can't upload it here, too big)

There is still a problem to fix because with the actual problem, we can't work and save with the game open.

**Comment by aMytho** [comment]
At first glance it looks alright. I'll run the code myself tomorrow.

I think the error is a Godot bug, rather than anything from the project. It is supposed to support auto-reloading but it doesn't always work. I've seen the error a few times myself. We can usually move elements around, but any code changes requires a restart. What specific change are you making when it crashes?

I'm waiting for Godot 4.1.x. They are on the dev snapshots, so it should be released soon. Hopefully that will fix this issue. I'm also hoping it will fix the typed array bug so we can drag/drop dialogue events. If we don't want to wait, we can upgrade to 4.0.3 when it releases. Should be within 2 weeks.

**Comment by Iruuka** [comment]
For the bug, while in file Menu/SubMenu/Unit/Display/view_units.gd, if I add a line (like just press enter key) between the for units and the previous var (or in the for) WHILE the game is on and if I save the file, it crash. _I believe you can have this problem anywhere in the file, but I didn't try it, neither in another file_

That's all I can give you for way to try the problem. I didn't get this problem earlier when just looking for how to get datas.

I'll take a gif record later today (it's past midnight rn so i'll go to sleep soon)

Edit 14/05/2023 - 11:15am GMT+2 : Just try using main branch and problem is here. Which is weird because I didn't have it before. So I'll make it so the branch is ready to review.

**Comment by aMytho** [comment]
I ran it myself, worked great. Its nice to see the units again. The project is slowly looking more like the original. I'll merge the PR.

I'm pretty certain the bug is a godot problem rather than a problem with our project. I had a similar issue when editing files while the editor was open on a separate branch.

**Pull request merged**
