### PR TITLE
Add Cave of Flames level (the first two atm)

### PR DESCRIPTION
**Pull request by Iruuka**
What does it add (for now) : 
- new dungeon : Cave of Flames
- new levels (only two for now)

What has been updated for it : 
- area.gd => instead of calling the .tres file for the dungeon, it would only use the adventure's prairie one + it would only show the adventure's prairie area name
- level_scrollable.gd ==> because I have pre-set the level number, there are some who are null. I added a verification to not continue with the current level when it's null

What is needed after that : 
- Implementation of the next levels of **Cave of FLames**
- Update some units because, with the PR https://github.com/aMytho/brave-frontier-godot/pull/38, the sprites of some units weren't set. Right now, I was working on unit **56 - Warlorck Liza** to add her sprite. You can see a file **unit_anim_idle_10041** which is the idle of Liza. The choice of this is because the Idle and Attack sprites are a bit different in size (i feel like). So it feels better to seperate each of them to easily import them in the sprite file,

### CODE REVIEW

**Comment by Iruuka** [comment]
Hello @aMytho 👋 
Here's a little PR for the level of **Cave of Flame**. I let you review it. It still needs some work, but we could use this PR as a base for **Cave of Flames**.
We would need to update the sprite of each units + add the others level of this Dungeon.

Also, I was wondering do we have a special attack animation for unit that attack from their seat ? Like Warlock Liza (see here https://www.youtube.com/watch?v=oBJ-k9D9sS4&list=PLsnvewLtPGlMPw6yLtfaq-5pD6LRCO-Ib&index=3&t=5583s). Is it implemented yet ? I'm sorry if you may have share it already before.

Don't hesitate to review it !

Have a good day and Happy New Year ! 🐧

**Comment by aMytho** [comment]
Happy New year, and thanks for the PR!

We can separate the two Liza spritesheets or keep them together. It doesn't really matter as long as they are all in the same spriteframes.
I did a lot of work on our animation system a while ago. We can add effects/equipment now. It can take a while to build the system for each unit, but we have a lot of customization options. [Unit Animations](https://github.com/aMytho/brave-frontier-godot/wiki/Unit-Animations)

At the moment we don't differentiate between attack animations. Our units just move to the enemy and attack, then move back. It looks like the real game had data that indicated if each unit had a teleport/walk/sit attack animation. I'm not sure if we want to implement that or not. Most of our units work in the current system, and [Catastrophic-Coder](https://github.com/Catastrophic-Coder) did some custom animation work for those that didn't. Magress (unit 21) is an example with a custom walking animation. Squire Atro (unit 17) had a teleport animation, so I just added blank frames for his travel animation to mimic the effect.

I can merge this now, or wait if you want to add more to it. I'm going to work on a proper progression system in the next few days. I started a simple one with godot resources, but it was game-wide, not account-wide, and it doesn't work in production. It shouldn't require any changes for this PR though.

**Comment by aMytho** [comment]
I merged #57 , but I don't think it will require any changes. I changed the `is_visible` zone property to `can_be_visible` and the DB now uses the IDs of zones to keep track of completions.

**Comment by aMytho** [comment]
I'll go ahead and merge this, sorry for the delay. IRL life has been keeping me pretty busy lately.

I'll see if I can add a property to hide existing dungeons if they are not yet playable. We can already do that with the individual zones, but we still need the ability for dungeons.

Edit: I added that property on the `dungeon_placement` for cave of flames in the mistral area file. Its hidden by default, at least until we have time to finish it 😄 . Hopefully I'll have more time to work on the project soon.

**Pull request merged**
