### PR TITLE
Add egor snowfield units + update old unit for sprite sheet + create …

### PR DESCRIPTION
**Pull request by Iruuka**
This PR does : 

- add new unit (without spritesheet yet) of the Egor Snowfield
- Update old unit by adding spritesheets
- Update Adventure Prairie level

### CODE REVIEW

**Comment by aMytho** [comment]
Looks good, this will be helpful for the first few levels. Thanks!

`desktop.ini` was accidentally included, it can be removed at `Units/Res/46/desktop.ini`

#42 changes the king slimes and the fire nymph sprites, but seeing as its being being merged into a different branch it will be fine for now. I can go through and move the atlas textures when `mistral-dungeons` is merged into main.

**Comment by Iruuka** [comment]
@aMytho I should have placed this PR as draft and try to finish the last level of Adventures's prairie before merging. After that, I'll go for the next Zone

For the updated units, i'll take care of it after this PR !

**Comment by aMytho** [comment]
Sounds good, I'll wait till then to merge it.

Edit: Sorry if the comment sent twice. I tried the replay via email, and I'm not entirely sure where the message went...

**Comment by Iruuka** [comment]
Hello @aMytho !

You can merge this PR ! (Or at least review it first !)
I've added the last zone of Adventurer prairie so every level is "ready". So now, there are all units for the 3 first zone of Mistral. But not all units have their spritesheet ready and no level selector are created for them yet
There is just 3 units which don't have the spritesheet ready so they can't be used yet. (3 or more, I might have missed some). And also the adventurer prairie won't show the new stage because I forgot to add them xD

I'll try to take this work in the next days (but as for this week, my mind isn't on it xD), but if anyone want to take this, I'll be glad to show them the actual problem ! The person in charge also have to take the new commits from main so we are still update.

Have a good Day/Night ! 🐧

**Comment by aMytho** [comment]
I'll get it merged 👍 

We can do the units/stages as we have time, it doesn't need to be all at once. Its not a huge priority, especially considering we could add them for weeks and still not be done lol. We will have a few extra areas to work with now.

For selecting units, we can add them manually from the DB. ( We should make a dev toolbox or something, I might work on that this weekend). I use sqlite studio. Its an easy interface for working with the DB. Once I have the unit ID I can manually insert a new row to add the unit to my collection.

Thanks!

**Pull request merged**
