### PR TITLE
Add Migrations, Teams

### PR DESCRIPTION
**Pull request by aMytho**
Will add a team selection to the level select.

Adds the migrations for units and teams into the DB. I thought this was already completed (oops). Once merged, you can run through the Tilith dialogue and load a level with your real units.

### CODE REVIEW

**Comment by Iruuka** [comment]
Looks fine for me.
Test it, data has been saved and could load a level.
I've just seen a mystake introduce by the https://github.com/aMytho/brave-frontier-godot/pull/5, witch i'll fix it (levels are set at 0 instead of 1 for units)

**Comment by aMytho** [comment]
Work in progress for the team selector. ATM its all preloaded data, will try to add the functionality tomorrow.
image

**Comment by aMytho** [comment]
This is turning into a bigger PR than I expected, but I added some important functionality.

## Resource Lookups
Autoload singleton file that lets us lookup unit info based on different ids. This is used in the teams page and will be useful later. The way our system works is each unit is a single resource with its base values. The database stores the units the player has collected with their overridable stats (atk, lvl, def, etc.). We use the lookup file to convert the database unit to the godot resource unit.

## Content Switcher
A simple menu that can dynamically load scenes with the classic menu animations. It is the same code as the unit menu. The unit menu will need to be moved to this format later.

You can now load your initial team via the new menus. I'll add the team switcher functionality soon. ATM, we only have 1 team anyway.

If anyone tests this PR, you will need to re-run the migrations. 1.sql has been updated.

**Comment by aMytho** [comment]
Demo of team switcher (the old units appearing is fixed in the next commit)

https://user-images.githubusercontent.com/58316242/232178253-fd927c24-7cd9-4823-8505-a3f22879e6e4.mp4

**Pull request merged**
